name: brasileirao_app
description: "Aplicativo do Campeonato Brasileiro"

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  fl_chart: ^0.65.0
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/escudos/